name: Automatically release and publish to nuget.org

# TODO: Run automatically
on:
  workflow_dispatch:

jobs:
  get-package-version:
    name: Get package version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-package-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Get package version
        id: get-package-version
        run: echo "version=$(dotnet build EHonda.HelloNuget --getProperty:Version)" >> "$GITHUB_OUTPUT"

  check-nuget-exists:
    name: Check nuget.org package exists
    runs-on: ubuntu-latest
    needs: get-package-version
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Check nuget.org package exists
        env:
          PACKAGE_VERSION: ${{ needs.get-package-version.outputs.version }}
        run: nuget help
