# TODO: Improvements
#         - Comments
#         - Better user output
name: Automatically release and publish to nuget.org

# TODO: Run automatically
on:
  #workflow_dispatch:
  push:
    branches:
      - main

jobs:
  get-package-metadata:
    # Deactivate for testing
    if: ${{ false }}
    name: Get package metadata
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.get-package-version.outputs.package-version }}
      package-id: ${{ steps.get-package-id.outputs.package-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Get package version
        id: get-package-version
        run: echo "package-version=$(dotnet build EHonda.HelloNuget --getProperty:PackageVersion)" >> "$GITHUB_OUTPUT"
      - name: Get package id
        id: get-package-id
        run: echo "package-id=$(dotnet build EHonda.HelloNuget --getProperty:PackageId)" >> "$GITHUB_OUTPUT"

  # TODO: Improvements:
  #         - Check if we're >= any existing version
  check-nuget-exists:
    # Deactivate for testing
    if: ${{ false }}
    name: Check nuget.org package exists
    runs-on: ubuntu-latest
    needs: get-package-metadata
    outputs:
      should-release: ${{ steps.check-nuget-exists.outputs.should-release }}
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Check nuget.org package exists
        id: check-nuget-exists
        env:
          PACKAGE_VERSION: ${{ needs.get-package-metadata.outputs.package-version }}
          PACKAGE_ID: ${{ needs.get-package-metadata.outputs.package-id }}
        run: |
          LATEST_PACKAGE=$(nuget list $PACKAGE_ID -Source https://api.nuget.org/v3/index.json)
          LATEST_VERSION=$(echo $LATEST_PACKAGE | awk '{print $NF}')
          if [ "$LATEST_VERSION" == "$PACKAGE_VERSION" ]; then
            echo -e "\e[32mINFO:\e[0m Package $PACKAGE_ID@$PACKAGE_VERSION already exists"
            echo "should-release=false" >> $GITHUB_OUTPUT
          else
            echo -e "\e[32mINFO:\e[0m Package $PACKAGE_ID@$PACKAGE_VERSION does not exist"
            echo "should-release=true" >> $GITHUB_OUTPUT
          fi

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      # Required to create the release
      contents: write
    # Deactivate for testing
    #needs: [get-package-metadata, check-nuget-exists]
    #if: needs.check-nuget-exists.outputs.should-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create release
        env:
          #PACKAGE_VERSION: ${{ needs.get-package-metadata.outputs.package-version }}
          # TODO: Set permissions on token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #run: gh release create "v$PACKAGE_VERSION" --generate-notes
        run: |
          gh auth status
          gh release list --repo ehonda/EHonda.HelloNuget
          gh release create "test" --draft --generate-notes
