name: Publish to nuget.org

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
      - run: dotnet pack --configuration Release --output ./publish
      - run: ls -la ./publish
