name: Test "should release" functionality

on:
    workflow_dispatch:

jobs:
    test-from-json:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo ${{ fromJson(true) }}
                echo ${{ fromJson(false) }}
                echo ${{ fromJson(1) }}
                echo ${{ fromJson(2) }}
                echo ${{ fromJson('$SOME_STRING') }}
              env:
                SOME_STRING: "string"

    check:
        runs-on: ubuntu-latest
        outputs:
            should_release: ${{ steps.should_release.outputs.should_release }}
        steps:
            - id: should_release
              run: echo "should_release=false" >> $GITHUB_OUTPUT

    release:
        needs: check
        if: fromJson(needs.check.outputs.should_release)
        runs-on: ubuntu-latest
        steps:
            - env:
                SHOULD_RELEASE: ${{ needs.check.outputs.should_release }}
              run: |
                echo "SHOULD_RELEASE=$SHOULD_RELEASE"
                echo "Releasing"
