name: Run dotnet tests

on:
  workflow_call:

jobs:
  test:
    name: Run dotnet tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Run dotnet tests
        run: dotnet test --configuration Release
