name: Verify Release

on:
  workflow_dispatch:

jobs:
  verify-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Verify Release
        run: dotnet build EHonda.HelloNuget --getProperty:Version
