name: Verify Release

on:
  #workflow_dispatch:
  release:
    types: [published]

jobs:
  get-package-version:
    name: Get package version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-package-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Get package version
        id: get-package-version
        run: echo "version=$(dotnet build EHonda.HelloNuget --getProperty:Version)" >> "$GITHUB_OUTPUT"

  verify-release:
    name: Verify release
    runs-on: ubuntu-latest
    needs: get-package-version
    steps:
      - name: Verify correct release version
        env:
          #RELEASE_VERSION: ${{ github.event.release.tag_name }}
          RELEASE_VERSION: $GITHUB_REF
          CSPROJ_VERSION: ${{ needs.get-package-version.outputs.version }}
        run: |
          if [ "$RELEASE_VERSION" != "$CSPROJ_VERSION" ]; then
            echo -e "\e[31mERR:\e[0m Release version ($RELEASE_VERSION) does not match csproj version ($CSPROJ_VERSION)"
            exit 1
          fi
